### ISSUE TITLE
"platform.js" has been renamed to "webcomponents.js"

### ISSUE THREAD

**Issue by mehaase** [dart-lang/dartdoc-viewer#123]
I'm trying to get started with dartdocgen and the dartdoc viewer. Dartdocgen works fine (I think) but the dartdoc viewer seems to be unmaintained.

    $ pubpub build
    Loading source assets... 
    Loading polymer/src/build/mirrors_remover, code_transformers/src/delete_file, observe and smoke/src/default_transformer transformers..Loading polymer/src/build/mirrors_remover, code_transformers/src/delete_file, observe and smoke/src/default_transformer transformers... 
    Loading polymer transformers... 
    Loading dartdoc_viewer transformers... 
    Building dartdoc_viewer... 
    [Warning from polymer (Linter) on dartdoc_viewer|web/index.html]:
    line 9, column 3 of web/index.html: "platform.js" has been renamed to "webcomponents.js". See http://goo.gl/5HPeuP#polymer_46 for details.
    <script src="packages/web_components/platform.js">
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [Warning from polymer (Linter) on dartdoc_viewer|web/index.html]:
    line 10, column 3 of web/index.html: No need to include "dart_support.js" by hand anymore. See http://goo.gl/5HPeuP#polymer_43 for details.
    <script src="packages/web_components/dart_support.js">
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [Warning from Analytics on dartdoc_viewer|web/index.html]:
    Could not find asset dartdoc_viewer|lib/config/config.yaml.
    null
    [Warning from Analytics on dartdoc_viewer|web/index.html]:
    No config used.
    [Info from Dart2JS]:
    Compiling dartdoc_viewer|web/index.html.0.dart...
    [Dart2JS on dartdoc_viewer|web/index.html.0.dart]:
    2 warning(s) suppressed in package:dartdoc_viewer.
    [Info from Dart2JS]:
    Took 0:00:10.289786 to compile dartdoc_viewer|web/index.html.0.dart.
    [Info from Dart2JS]:
    Compiling dartdoc_viewer|web/index.html_bootstrap.dart...
    [Dart2JS on dartdoc_viewer|web/index.html_bootstrap.dart]:
    2 warning(s) suppressed in package:dartdoc_viewer.
    [Info from Dart2JS]:
    Took 0:00:06.446011 to compile dartdoc_viewer|web/index.html_bootstrap.dart.
    Built 86 files to "build".

They're jus warnings, so I cross my fingers and hope it works anyway. But when I view this in a browser (Chrome), I see:

    Failed to load resource: the server responded with a status of 404 (File not found)
    http://localhost:8000/packages/web_components/platform.js

This is on master (7d7610). It seems that platform.js was renamed [months ago|https://blog.polymer-project.org/announcements/2014/10/16/platform-becomes-webcomponents/] but dartdoc viewer hasn't been updated to match? Am I crazy, or is dartdoc viewer totally broken? I can't be the only person to install dartdoc viewer in the last 2 months.

If I make the suggested changes, I still get the following error:

    Uncaught ReferenceError: HTMLImports is not defined 

Now I'm totally stumped. I think this might be a problem in Polymer, but this whole stack is new to me and it's got a lot of moving pieces and magical bits.

Here's what I'm running:

* Dartium Version 38.0.2125.0 (292384) (64-bit)
* HTML5lib 0.12.0
* Polymer 0.15.3+2
* Polymer Expressions 0.13.0+1
* Web Components 0.10.0

Any advice?

**Comment by alan-knight** [comment]
Did you by any chance do a pub upgrade? The viewer is checked in with a
pubspec.lock file because it's set up to use a particular version of
polymer. Polymer is still changing rapidly, so it probably won't work if
you're trying to use the viewer with a newer version of polymer. But I used
it the other day without any problem. I suppose Dartium might be an issue
if the Dartium version forces an SDK that's incompatible with the older
polymer. Does it work if compiled to JS?

**Comment by mehaase** [comment]
No changes to pubspec.lock. The 2 breaking changes in Polymer [were introduced in 0.15.1 and 0.15.2](https://www.dartlang.org/polymer/reference/release-notes/#polymer-0152), and the pubspec.lock says 0.15.3+2 (this was updated in the most recent commit on Dec 15th).

I can compile it to JavaScript successfully, but I get the same reference error.

**Comment by alan-knight** [comment]
Took a look. It doesn't work at all in Dartium, but not because of platform.js, because it explicitly forces use of the shadow DOM polyfill rather than native shadow DOM so that bootstrap styles will apply to all the elements. Dartium doesn't allow this. This is annoying, and should be fixed, but fixing up the styles is good deal of work. I'm hoping that https://github.com/dart-lang/dartdoc will come along quickly enough to not have to do it.

But I take 7d76102, run pub build (it does warn about platform.js and dart_suport.js, but works), change into build/web, run python -m SimpleHTTPServer, and connect to localhost:8000, and it runs fine in Chrome up until the point where it goes to look for docs and doesn't find any.

Or, the simplest way to run it on real docs is with 
    dartdocgen --serve .
which also seems to be fine.

**Comment by sethladd** [comment]
dartdoc is coming along, but not quite ready.

Perhaps we just say that you need to use Chrome (and not Dartium) to work with dartdoc-viewer for now.

**Comment by mehaase** [comment]
Thanks, Alan. Your reply helped me figure out what I was doing wrong. I was doing two things wrong, actually.

1. The [README](https://github.com/dart-lang/dartdoc-viewer/) says "start a simple server while standing in the *top level of this package*". I had interpreted that as meaning inside `client/web`, not `client/build/web`. Guess I'm still getting used to the Dart ecosystem, but that wasn't obvious to me.
2. The README also says "place the JSON files generated from docgen in client/local", but that doesn't work for me. If I understand what the README is saying, then I should have `index.json` stored at `client/local/index.json`, right? But the viewer looks for it in `/docs/index.json` and I don't have a 'docs' directory in client/build/web. I was able to get it working by copying my JSON docs into `client/build/web/docs` but that doesn't seem to be what the instructions are suggesting.

Other newbies might appreciate some additional details in the instructions. (I would volunteer to write it, but don't trust my own familiarity with it.)

**Comment by alan-knight** [comment]
Yeah, that's confusing, part of it temporary, and part of it because this package is confusing. The top level of this package would be right if you were running in Dartium. That might even mean client, not client/web, I'm not sure. And the fact that it doesn't work in Dartium is a weird temporary artifact, and one which makes it tricky to work on. 

With pub build it generates the compiled version into the build/ directory. That's normal pub behaviour, but if you're not used to using it, you wouldn't be expected to know. The easier thing to do is use pub serve, where it runs its own server and does the build for you.

Where the doc files go varies depending on what configuration this is deployed in, which is part of what makes this a confusing package. It's different if it's being built for dartdocs.org, or for api.dartlang.org, or running locally. The easy path for using it locally is to have dartdocgen do it for you, thus the --serve option. But it's definitely more confusing than most Dart packages. And it is not being actively developed because the new thing is the dartdoc package, which just generates static files which should be easier to work with. Sorry for the confusion.
